Repository spa5k/quran, pull requests merged in 2023-01, with the labels that each got.

#30 feat(refactor): ♻️ refactored few types and updated rspc
  .cargo/config.toml
  .vscode/settings.json
  iqra/Cargo.toml
  iqra/src/api/mod.rs
  iqra/src/queries/surah.rs
  pnpm-lock.yaml
  tanzil/package.json
  tanzil/src/features/surahs/api/index.ts
  tanzil/src/pages/index.tsx
  tanzil/src/pages/surah/[id].tsx
  tanzil/src/utils/bindings.ts
  tanzil/src/utils/rspc.ts
  tanzil/tsconfig.json
Labels: Large

#32 feat(tanzil): ♻️ added vite plugins and updated a few things
  README.md
  dprint.json
  pnpm-lock.yaml
  tanzil/.eslintrc-auto-import.json
  tanzil/.eslintrc.cjs
  tanzil/index.html
  tanzil/package.json
  tanzil/postcss.config.cjs
  tanzil/src/auto-import.d.ts
  tanzil/src/main.css
  tanzil/src/main.tsx
  tanzil/src/pages/index.tsx
  tanzil/src/pages/surah/[id].tsx
  tanzil/src/utils/index.ts
  tanzil/src/utils/rspc.ts
  tanzil/tailwind.config.cjs
  tanzil/vite.config.ts
Labels: Extra Large

#36 feat(github): 💚 added 2 github actions
  .github/workflows/codeball.yml
  .github/workflows/linter.yml
  .vscode/settings.json
  sonar-project.properties
Labels: Small, codeball:approved

#41 feat(tailwind): ✨ added theme changer of tailwind
  .cargo/config.toml
  .vscode/settings.json
  README.md
  pnpm-lock.yaml
  tanzil/.eslintrc-auto-import.json
  tanzil/package.json
  tanzil/postcss.config.cjs
  tanzil/src/auto-import.d.ts
  tanzil/src/features/surahs/api/index.ts
  tanzil/src/index.css
  tanzil/src/main.css
  tanzil/src/main.tsx
  tanzil/src/pages/index.tsx
  tanzil/src/pages/surah/[id].tsx
  tanzil/src/screens/homepage.tsx
  tanzil/src/stores/theme.ts
  tanzil/tailwind.config.cjs
  tanzil/vite.config.ts
Labels: Large

#47 ci(github): 💚 adding issue bot
  .github/issue-branch.yml
Labels: Extra Small

#61 feat: :sparkles: Issue 42 initial layout nothing else
  tanzil/index.html
  tanzil/public/favicon.svg
  tanzil/public/vite.svg
  tanzil/src/components/LeftBar.tsx
  tanzil/src/components/MainContent.tsx
  tanzil/src/components/RighBar.tsx
  tanzil/src/pages/index.tsx
  tanzil/src/screens/homepage.tsx
Labels: Small, codeball:needs-careful-review

#81 Added next salah and salah times function
  iqra/Cargo.toml
  iqra/src/queries/iqama.rs
Labels: Extra Small

#88 feat: :sparkles: removing tailwind css file
  iqra/Cargo.toml
  iqra/src/queries/iqama.rs
  tanzil/.gitignore
  tanzil/public/tailwind.css
Labels: Extra Large, codeball:needs-careful-review
