Repository spa5k/quran, pull requests merged in 2023-02, with the labels that each got.

#139 feat: :sparkles: Added basic salah times using adhan library
  package.json
  pnpm-lock.yaml
  tanzil/src/auto-import.d.ts
  tanzil/src/pages/salah/index.tsx
Labels: Extra Large, codeball:needs-careful-review

#142 feat: :sparkles: add salah times aka prayer times with geolocation
  package.json
  packages/eslint-config-custom/package.json
  packages/scraper/package.json
  pnpm-lock.yaml
  tanzil/package.json
  tanzil/src/auto-import.d.ts
  tanzil/src/components/Card/card.tsx
  tanzil/src/components/Layout/LeftBar.tsx
  tanzil/src/features/index.ts
  tanzil/src/features/salah/api/index.ts
  tanzil/src/features/salah/index.ts
  tanzil/src/features/salah/types/index.ts
  tanzil/src/pages/_app.tsx
  tanzil/src/pages/salah/index.tsx
  tanzil/src/stores/salah.ts
  tanzil/vite.config.ts
Labels: codeball:needs-careful-review

#146 feat: :sparkles: fix(salah): 🐛 fixing the salah timing loading inconsistently
  .vscode/settings.json
  iqra/Cargo.lock
  packages/scraper/package.json
  pnpm-lock.yaml
  tanzil/package.json
  tanzil/src/pages/salah/index.tsx
  tanzil/src/stores/salah.ts
Labels: Large, codeball:needs-careful-review
